### PR TITLE
Additional fiat currencies

### PR DESCRIPTION
**Pull request by hellc**
Additional fiat currencies (RUB, DKK, SGD, THB)

Update endpoint to support following currencies
`https://usxvglw.vergecoreteam.com/price/api/v1/price/RUB` or etc

## Related Issue
https://github.com/vergecurrency/vIOS/issues/69

## Motivation and Context
We need more currencies support for international stores usage
I need Russian Ruble for myself

## Types of changes
- [x] Update endpoint _/price/api/v1/price/_ to support related currencies
- [x] Test / Deploy

### CODE REVIEW

**Comment by SwenVanZanten** [comment]
Thank you awesome! 💪 

Actually the currency API behind it is this repo 😄 
https://github.com/vergecurrency/verge-price-ticker

**Comment by hellc** [comment]
@SwenVanZanten  Updated, need to test and deploy

**Comment by SwenVanZanten** [comment]
Awesome thanks!
@marpme can you test & deploy https://github.com/vergecurrency/verge-price-ticker/pull/2

**Comment by SwenVanZanten** [comment]
Thanks for your contribution 💪 
Don't forget to add yourself to the credits view is you want to 😉

**Comment by hellc** [comment]
> Thanks for your contribution 💪
> Don't forget to add yourself to the credits view is you want to 😉

For sure :)

**Pull request merged**
