### PR TITLE
Contact creation UX / Address validator

### PR DESCRIPTION
**Pull request by hellc**
## Description
Address validator updated
Contact creation/edit UX updated (pop screen on save/creation)
Contact model updated

## Related Issues
https://github.com/vergecurrency/vIOS/issues/64
https://github.com/vergecurrency/vIOS/issues/53

## Motivation and Context
Contact creation UX was simplified and w/o proper validation

### CODE REVIEW

**Comment by marpme** [comment]
Well the address could be checked if more detailed, via decoding it from base58

1. Remove the last 4 bytes of the decoded byte array (store it, it's the checksum)
2. Take the rest of the array and do `let checksum = sha256(sha256(restArray))`
3. Check if valid `checksumStored == checksum[0..8]`

**Comment by hellc** [comment]
@marpme I guess we need another PR for address validation context only. Right now it's just an updated version of the previous one in case of contact creation/validation. Also I suggest you to make address validator as static.

**Comment by marpme** [comment]
@hellc okay, I agree with you but let's bring this into a new issue as I saw that there are no security checks overall for addresses. Just worrying.

**Comment by SwenVanZanten** [comment]
@hellc I don't see a problem in making it static

**Comment by hellc** [comment]
> @hellc I don't see a problem in making it static

Ok. Got it. Here is the issue https://github.com/vergecurrency/vIOS/issues/84 for the new PR.

So, I have nothing to update in current PR right now. If it's ok, you could merge it too. =)

**Comment by SwenVanZanten** [comment]
Thank you!

**Pull request merged**
