### PR TITLE
bans feature / dns based wallet address / wallet short names

### PR DESCRIPTION
**Pull request by hellc**
## Description
We could easily provide short names in XVG wallets using secured DNS.
Here is some description of my DNS method: https://github.com/hellc/bans
Here is the short demo video: https://youtu.be/A94jY8ZhCbA

## Motivation and Context
I don't like [this](https://www.coindesk.com/ethereum-is-getting-its-first-top-level-domain-name/) sloppy method. I think we could do it more easily and accessibly.

### CODE REVIEW

**Comment by SwenVanZanten** [comment]
@hellc Thank you for your contribution! 💯 

We don't have any plans yet to integrate this into the wallet.
To be honest we don't really think people want/need such a feature.
But we'll leave the PR open so I there is some interests in this feature we can still integrate it.

✌️ Thank you

**Comment by hellc** [comment]
@SwenVanZanten  If you want you could also check Ethereum activity due the DNS usage to get motivation too :) 
In our case we could initiate more freedom way of DNS re-usage. How else could do that, no one knows about **bans**, come on...

Anyway we could also create an option in settings that could enable/disable BANS feature.

> PS: Short human readable addresses sounds good for me as PR/Marketing feature. That's could be good for donation cases etc. (ex. wikipedia.org)

**Comment by SwenVanZanten** [comment]
Do you know of any possible security issues this might bring?

And I think instead of having a separate input field it might be a better idea to just use the address field. If theres a domain name in the field it could resolve the bans itself. What do you think about that? And maybe the explanation on it could be in a modal under a BarButtonItem on the right?

**Comment by marpme** [comment]
DNS idea is great 👍 don’t get wrong but it feels like that it’s the wrong application level to establish such a address research in my opinion. 

Not sure if you are familiar with PGP/GnuPG, but they have developed an established and well working decentralized network structure to have a simple key storage for email address. That means everyone can simply upload the public (with the email address) to the pool network so everyone can get a key by downloading the public key.

This scenario could be easily applied for our use case and feels more natural than handing out pure addresses (can not proof its your address, which I can with this key server)

**Pull request closed without merging**
